name: Bandit Code Scanning and Blocking (Public Repo)

on:
  pull_request:
    branches: [ main ]  # Adjust the protected branch name if needed 

jobs:
  bandit-scan:
    name: Run Bandit Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Bandit
        run: |
          python -m pip install bandit
      - name: Run Bandit Scan
        run: bandit -f json -o bandit_results.json .

      - name: Parse Bandit Results and Fail on Critical Issues
        id: analyze_results
        run: |
          vulnerabilities=$(jq -r '.results[] | select(.severity == "CRITICAL") | @csv' bandit_results.json)
          if [[ ! -z "$vulnerabilities" ]]; then
            echo "::error:: BLOCK"
            echo "List of critical vulnerabilities:"
            echo "$vulnerabilities"
            exit 1  # Fail the job if critical issues are found
          else
            echo "Bandit scan successful! No critical vulnerabilities found."
          fi
